/**
 *  @author Ana Lucia Hernandez (17137)
 *          Alexander Trujillo (17189)
 *  @since 02.11.17
 *  Clase que realiza toda la interaccion con el usuario. 
 *  AcueductoUI.java
 **/
package Acueducto;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class AcueductoUI extends javax.swing.JFrame {

    /**
     * Creates new form AcueductoUI
     */
    Acueducto acueducto;
    BaseDeDatos db;
    public AcueductoUI() {
        initComponents();
        acueducto = new Acueducto();
        db = new BaseDeDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresarTanque = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        dimCub = new javax.swing.JLabel();
        dimCil = new javax.swing.JLabel();
        dimOrt = new javax.swing.JLabel();
        lado = new javax.swing.JLabel();
        largoO = new javax.swing.JLabel();
        anchoO = new javax.swing.JLabel();
        altoO = new javax.swing.JLabel();
        ladoCubico = new javax.swing.JTextField();
        largoOrt = new javax.swing.JTextField();
        anchoOrt = new javax.swing.JTextField();
        altoOrt = new javax.swing.JTextField();
        radio = new javax.swing.JLabel();
        radiotxt = new javax.swing.JTextField();
        altoCil = new javax.swing.JLabel();
        altocilin = new javax.swing.JTextField();
        agregarTanque = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        municipio1 = new javax.swing.JTextField();
        municipio2 = new javax.swing.JTextField();
        municipio3 = new javax.swing.JTextField();
        municipio4 = new javax.swing.JTextField();
        municipio5 = new javax.swing.JTextField();
        municipio6 = new javax.swing.JTextField();
        municipio7 = new javax.swing.JTextField();
        municipio8 = new javax.swing.JTextField();
        municipio9 = new javax.swing.JTextField();
        municipio10 = new javax.swing.JTextField();
        habitantes1 = new javax.swing.JTextField();
        habitantes2 = new javax.swing.JTextField();
        habitantes3 = new javax.swing.JTextField();
        habitantes4 = new javax.swing.JTextField();
        habitantes5 = new javax.swing.JTextField();
        habitantes6 = new javax.swing.JTextField();
        habitantes7 = new javax.swing.JTextField();
        habitantes8 = new javax.swing.JTextField();
        habitantes9 = new javax.swing.JTextField();
        habitantes10 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        regionNT = new javax.swing.JTextField();
        formaCB = new javax.swing.JComboBox<>();
        seguirNTanque = new javax.swing.JButton();
        numeroNT = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        numeroAV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        municipioAV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        calendarioAV = new com.toedter.calendar.JDateChooser();
        abrirValvula = new javax.swing.JButton();
        cerrarValvula = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        numeroLT = new javax.swing.JTextField();
        llenarTanque = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTanques = new javax.swing.JTextArea();
        mostrarTanques = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        regionCA = new javax.swing.JTextField();
        mostrarAgua = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        aguaCA = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        cantidadValvulas = new javax.swing.JTextField();
        mostrarValvulas = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso de datos del nuevo tanque", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        dimCub.setText("Dimensiones del tanque (metros)");

        dimCil.setText("Dimensiones del tanque (metros)");

        dimOrt.setText("Dimensiones del tanque (metros)");

        lado.setText("Lado:");

        largoO.setText("Largo:");

        anchoO.setText("Ancho:");

        altoO.setText("Altura:");

        radio.setText("Radio:");

        altoCil.setText("Altura");

        agregarTanque.setText("Agregar tanque");
        agregarTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTanqueActionPerformed(evt);
            }
        });

        jLabel13.setText("Nombre del municipio");

        jLabel14.setText("Habitantes del municipio");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(largoO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(largoOrt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anchoO)
                        .addGap(2, 2, 2)
                        .addComponent(anchoOrt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(altoO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(altoOrt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dimCub)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(lado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ladoCubico, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dimOrt)
                                    .addComponent(dimCil)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(radio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radiotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(altoCil)
                                        .addGap(2, 2, 2)
                                        .addComponent(altocilin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(agregarTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(municipio6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(municipio3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(habitantes2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dimCub)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lado)
                            .addComponent(ladoCubico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dimOrt)
                            .addComponent(municipio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(largoO)
                            .addComponent(anchoO)
                            .addComponent(altoO)
                            .addComponent(largoOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anchoOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altoOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dimCil)
                            .addComponent(municipio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio)
                            .addComponent(altoCil)
                            .addComponent(radiotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altocilin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(municipio6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(municipio7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitantes7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(agregarTanque)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(municipio8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(habitantes8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(municipio9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(habitantes9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(municipio10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(habitantes10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ingresarTanqueLayout = new javax.swing.GroupLayout(ingresarTanque.getContentPane());
        ingresarTanque.getContentPane().setLayout(ingresarTanqueLayout);
        ingresarTanqueLayout.setHorizontalGroup(
            ingresarTanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarTanqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        ingresarTanqueLayout.setVerticalGroup(
            ingresarTanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresarTanqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACUEDUCTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar nuevo tanque"));

        jLabel1.setText("Número de tanque");

        jLabel2.setText("Región a la que provee");

        jLabel3.setText("Forma del tanque");

        regionNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionNTActionPerformed(evt);
            }
        });

        formaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cúbico", "Cilíndrico", "Ortogonal" }));

        seguirNTanque.setText("Seguir");
        seguirNTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguirNTanqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(regionNT)
                            .addComponent(formaCB, 0, 177, Short.MAX_VALUE)
                            .addComponent(numeroNT)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(seguirNTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numeroNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(regionNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(formaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(seguirNTanque)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Abrir o cerrar la válvula de un tanque"));

        jLabel4.setText("Número de tanque");

        numeroAV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroAVActionPerformed(evt);
            }
        });

        jLabel5.setText("Municipio al que alimenta la válvula");

        municipioAV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioAVActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha de la acción");

        abrirValvula.setText("Abrir válvula");
        abrirValvula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirValvulaActionPerformed(evt);
            }
        });

        cerrarValvula.setText("Cerrar válvula");
        cerrarValvula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarValvulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(59, 59, 59)
                                .addComponent(numeroAV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(municipioAV))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(45, 45, 45)
                                .addComponent(calendarioAV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(abrirValvula, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(cerrarValvula, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numeroAV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(municipioAV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(calendarioAV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abrirValvula)
                    .addComponent(cerrarValvula))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Llenar un tanque con agua"));

        jLabel7.setText("Número de tanque");

        numeroLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroLTActionPerformed(evt);
            }
        });

        llenarTanque.setText("Llenar tanque");
        llenarTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llenarTanqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(numeroLT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(llenarTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(numeroLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(llenarTanque)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de tanques que actualmente tiene el acueducto"));

        listaTanques.setColumns(20);
        listaTanques.setRows(5);
        jScrollPane1.setViewportView(listaTanques);

        mostrarTanques.setText("Actualizar lista de tanques");
        mostrarTanques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTanquesActionPerformed(evt);
            }
        });

        jLabel11.setText("** Hacer clic en Actualizar después de cualquier cambio");

        jLabel10.setText("y también al iniciar el programa");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(mostrarTanques))
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarTanques)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de agua disponible a para una región específica"));

        jLabel8.setText("Región");

        mostrarAgua.setText("Mostrar cantidad de agua disponible");
        mostrarAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAguaActionPerformed(evt);
            }
        });

        jLabel9.setText("Cantidad de agua disponible");

        aguaCA.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aguaCA, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(51, 51, 51)
                                .addComponent(regionCA, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(mostrarAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(regionCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(aguaCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mostrarAgua))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de válvulas abiertas de tanques cilíndricos"));

        cantidadValvulas.setEditable(false);

        mostrarValvulas.setText("Mostrar");
        mostrarValvulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarValvulasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(cantidadValvulas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(mostrarValvulas, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadValvulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarValvulas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("La siguiente simulación representa un solo día de consumo de agua en el acueducto Albear.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regionNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regionNTActionPerformed

    private void numeroAVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroAVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroAVActionPerformed

    private void municipioAVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioAVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioAVActionPerformed

    private void abrirValvulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirValvulaActionPerformed
        try
        {
            String IDtanque = numeroAV.getText();
            String municipio = municipioAV.getText().toUpperCase();
            DateFormat date = new SimpleDateFormat("dd-MM-yyyy");
            String fecha = date.format(calendarioAV.getDate());
            try 
            {
                if(IDtanque.equals("") || municipio.equals(""))
                {
                    JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    porcentajeLow.porcentajeLow(db.getPorcentajeTanque(IDtanque));
                    if (db.abrirValvula(IDtanque, municipio, fecha) == true)
                    {
                        JOptionPane.showMessageDialog(null, "La válvula indicada ha sido abierta con éxito.", "",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else 
                    {
                        JOptionPane.showMessageDialog(null, " La válvula que ha indicado no existe. \n Intente de nuevo.", "ERROR",JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            catch(AguaBajaException exc)
            {
                JOptionPane.showMessageDialog(null, exc.getMessage(), "ALERTA",JOptionPane.ERROR_MESSAGE);
                if (exc.getPorcentaje() <= 10)
                {
                    db.cerrarTodasValvulas(IDtanque, fecha);
                }
            }
        }
        catch (NullPointerException e)
        {
            JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_abrirValvulaActionPerformed

    private void cerrarValvulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarValvulaActionPerformed
        try
        {
            String IDtanque = numeroAV.getText();
            String municipio = municipioAV.getText().toUpperCase();
            if(IDtanque.equals("") || municipio.equals(""))
                {
                    JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    DateFormat date = new SimpleDateFormat("dd-MM-yyyy");
                    String fecha = date.format(calendarioAV.getDate());
                    db.cerrarValvula(IDtanque, municipio, fecha);
                    JOptionPane.showMessageDialog(null, "La válvula indicada ha sido cerrada con éxito.", "",JOptionPane.INFORMATION_MESSAGE);
                }
        }
        catch (NullPointerException e)
        {
            JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_cerrarValvulaActionPerformed

    private void numeroLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroLTActionPerformed
        
    }//GEN-LAST:event_numeroLTActionPerformed

    private void seguirNTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguirNTanqueActionPerformed
        
        try 
        {
            if(numeroNT.getText().equals("") || regionNT.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                Long.parseLong(numeroNT.getText());
                ingresarTanque.pack();
                ingresarTanque.setVisible(true);

                if (String.valueOf(formaCB.getSelectedItem()).equals("Cúbico"))
                {
                    lado.setVisible(true);
                    dimCub.setVisible(true);
                    ladoCubico.setVisible(true);
                    largoO.setVisible(false);
                    anchoO.setVisible(false);
                    altoO.setVisible(false);
                    largoOrt.setVisible(false);
                    anchoOrt.setVisible(false);
                    altoOrt.setVisible(false);
                    dimOrt.setVisible(false);
                    dimCil.setVisible(false);
                    radio.setVisible(false);
                    radiotxt.setVisible(false);
                    altoCil.setVisible(false);
                    altocilin.setVisible(false);
                }
                if (String.valueOf(formaCB.getSelectedItem()).equals("Ortogonal"))
                {
                    largoO.setVisible(true);
                    anchoO.setVisible(true);
                    altoO.setVisible(true);
                    largoOrt.setVisible(true);
                    anchoOrt.setVisible(true);
                    altoOrt.setVisible(true);
                    lado.setVisible(false);
                    dimCub.setVisible(false);
                    ladoCubico.setVisible(false);
                    dimOrt.setVisible(false);
                    dimCil.setVisible(false);
                    radio.setVisible(false);
                    radiotxt.setVisible(false);
                    altoCil.setVisible(false);
                    altocilin.setVisible(false);
                }
                if (String.valueOf(formaCB.getSelectedItem()).equals("Cilíndrico"))
                {
                    largoO.setVisible(false);
                    anchoO.setVisible(false);
                    altoO.setVisible(false);
                    largoOrt.setVisible(false);
                    anchoOrt.setVisible(false);
                    altoOrt.setVisible(false);
                    lado.setVisible(false);
                    dimCub.setVisible(false);
                    ladoCubico.setVisible(false);
                    dimOrt.setVisible(false);
                    dimCil.setVisible(true);
                    radio.setVisible(true);
                    radiotxt.setVisible(true);
                    altoCil.setVisible(true);
                    altocilin.setVisible(true);

                }
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Porfavor ingrese los datos correctamente.", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_seguirNTanqueActionPerformed

    private void mostrarValvulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarValvulasActionPerformed
        cantidadValvulas.setText(String.valueOf(db.valvulasC()));
    }//GEN-LAST:event_mostrarValvulasActionPerformed

    private void mostrarTanquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTanquesActionPerformed
        listaTanques.setText(db.buscarTanques());
    }//GEN-LAST:event_mostrarTanquesActionPerformed

    private void llenarTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llenarTanqueActionPerformed
        String numero = numeroLT.getText();
        if(numeroLT.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
            if (db.updateLlenado(numero) == true)
            {
                JOptionPane.showMessageDialog(null, "Se ha llenado el tanque con éxito.", "",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, " El tanque que ha indicado no existe. \n Intente de nuevo.", "ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_llenarTanqueActionPerformed

    private void mostrarAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAguaActionPerformed
        String region = regionCA.getText().toUpperCase();
        if (region.equals(""))
        {
            JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            aguaCA.setText(String.valueOf(db.aguaDisponible(region))+ " m^3");
        }
    }//GEN-LAST:event_mostrarAguaActionPerformed

    private void agregarTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTanqueActionPerformed
        String[] municipios = new String[10];
        long[] habitantes = new long[10];
        JTextField[] hab = {habitantes1,habitantes2,habitantes3,habitantes4,habitantes5,habitantes6,habitantes7,habitantes8,habitantes9,habitantes10};
        JTextField[] texto = {municipio1,municipio2,municipio3,municipio4,municipio5,municipio6,municipio7,municipio8,municipio9,municipio10};
        int i =0;
        try 
        {
            String numero = numeroNT.getText();
            String region = regionNT.getText().toUpperCase();
            if (String.valueOf(formaCB.getSelectedItem()).equals("Cúbico"))
            {
                if(ladoCubico.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(null, " No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
                    i=1;
                }
                else
                {
                    for (int t=0; t<10; t++)
                    {
                        if (texto[t].getText().equals(""))
                        {
                            JOptionPane.showMessageDialog(null, " No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
                            i=1;
                            break;
                        }
                        else
                        {
                            municipios[t] = texto[t].getText().toUpperCase();
                            for (int k =0; k<10; k++)
                            {
                                try 
                                {
                                    if(hab[k].getText().equals(""))
                                    {
                                        JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
                                        i=1;
                                        break;
                                    }
                                    else
                                    {
                                        habitantes[k] = Long.parseLong(hab[k].getText());
                                    }
                                }
                                catch (NumberFormatException e)
                                {
                                    JOptionPane.showMessageDialog(null, "Porfavor ingrese los datos correctamente.", "ERROR",JOptionPane.ERROR_MESSAGE);
                                    i=1;
                                    break;
                                }
                            }
                        }

                    }
                    if(i ==0)
                    {
                        db.ingresarTanque("Cubico", numero, municipios, habitantes, region, 0.0, 0.0, 0.0, 0.0, 0.0, Double.parseDouble(ladoCubico.getText()));
                        JOptionPane.showMessageDialog(null, "El tanque ha sido ingresado con éxito.", "",JOptionPane.INFORMATION_MESSAGE);
                        ladoCubico.setText("");
                        for (int l=0; l<10; l++)
                        {
                            hab[l].setText("");
                            texto[l].setText("");
                        }
                    }
                }
            }
            if (String.valueOf(formaCB.getSelectedItem()).equals("Ortogonal"))
            {
                if(anchoOrt.getText().equals("") || altoOrt.getText().equals("") || largoOrt.getText().equals("") )
                {
                    JOptionPane.showMessageDialog(null, "Porfavor ingrese los datos correctamente.", "ERROR",JOptionPane.ERROR_MESSAGE);
                    i=1;
                }
                else
                {
                    for (int t=0; t<10; t++)
                    {
                        if (texto[t].getText().equals(""))
                        {
                            JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
                            i=1;
                            break;
                        }
                        else
                        {
                            municipios[t] = texto[t].getText().toUpperCase();
                            try
                            {
                                for (int k =0; k<10; k++)
                                {
                                    if(hab[k].getText().equals(""))
                                    {
                                        JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
                                        i=1;
                                        break;
                                    }
                                    else
                                    {
                                        habitantes[k] = Long.parseLong(hab[k].getText());
                                    }
                                }
                            }
                            catch (NumberFormatException e)
                            {
                                JOptionPane.showMessageDialog(null, "Porfavor ingrese los datos correctamente.", "ERROR",JOptionPane.ERROR_MESSAGE);
                                i=1;
                                break;
                            }
                        }
                    }
                    if (i==0)
                    {
                        db.ingresarTanque("Ortogonal", numero, municipios, habitantes, region, 0.0, 0.0, Double.parseDouble(anchoOrt.getText()), Double.parseDouble(altoOrt.getText()), Double.parseDouble(largoOrt.getText()), 0.0);
                        JOptionPane.showMessageDialog(null, "El tanque ha sido ingresado con éxito.", "",JOptionPane.INFORMATION_MESSAGE);
                        anchoOrt.setText("");
                        altoOrt.setText("");
                        largoOrt.setText("");
                        for (int l=0; l<10; l++)
                        {
                            hab[l].setText("");
                            texto[l].setText("");
                        }
                    }
                }
            }
            if (String.valueOf(formaCB.getSelectedItem()).equals("Cilíndrico"))
            {
                if(radiotxt.getText().equals("") || altocilin.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(null, "Porfavor ingrese los datos correctamente.", "ERROR",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    for (int t=0; t<10; t++)
                    {
                        if (texto[t].getText().equals(""))
                        {
                            JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
                            i=1;
                            break;
                        }
                        else
                        {
                            municipios[t] = texto[t].getText().toUpperCase();
                            for (int k =0; k<10; k++)
                            {
                                try 
                                {
                                    if(hab[k].getText().equals(""))
                                    {
                                        JOptionPane.showMessageDialog(null, "No puede dejar espacios vacios. \n Porfavor ingrese los datos requeridos.", "ERROR",JOptionPane.ERROR_MESSAGE);
                                        i=1;
                                        break;
                                    }
                                    else
                                    {
                                        habitantes[k] = Long.parseLong(hab[k].getText());
                                    }
                                }
                                catch (NumberFormatException e)
                                {
                                    JOptionPane.showMessageDialog(null, "Porfavor ingrese los datos correctamente.", "ERROR",JOptionPane.ERROR_MESSAGE);
                                    i=1;
                                    break;
                                }
                            }
                        }
                    }
                    if(i==0)
                    {
                        db.ingresarTanque("Cilindrico", numero, municipios, habitantes, region, Double.parseDouble(radiotxt.getText()), Double.parseDouble(altocilin.getText()), 0.0, 0.0, 0.0, 0.0);
                        JOptionPane.showMessageDialog(null, "El tanque ha sido ingresado con éxito.", "",JOptionPane.INFORMATION_MESSAGE);
                        radiotxt.setText("");
                        altocilin.setText("");
                        for (int l=0; l<10; l++)
                        {
                            hab[l].setText("");
                            texto[l].setText("");
                        }
                    }
                }
            }
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Porfavor ingrese los datos correctamente.", "ERROR",JOptionPane.ERROR_MESSAGE);

        }
        
    }//GEN-LAST:event_agregarTanqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcueductoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcueductoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcueductoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcueductoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcueductoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirValvula;
    private javax.swing.JButton agregarTanque;
    private javax.swing.JTextField aguaCA;
    private javax.swing.JLabel altoCil;
    private javax.swing.JLabel altoO;
    private javax.swing.JTextField altoOrt;
    private javax.swing.JTextField altocilin;
    private javax.swing.JLabel anchoO;
    private javax.swing.JTextField anchoOrt;
    private com.toedter.calendar.JDateChooser calendarioAV;
    private javax.swing.JTextField cantidadValvulas;
    private javax.swing.JButton cerrarValvula;
    private javax.swing.JLabel dimCil;
    private javax.swing.JLabel dimCub;
    private javax.swing.JLabel dimOrt;
    private javax.swing.JComboBox<String> formaCB;
    private javax.swing.JTextField habitantes1;
    private javax.swing.JTextField habitantes10;
    private javax.swing.JTextField habitantes2;
    private javax.swing.JTextField habitantes3;
    private javax.swing.JTextField habitantes4;
    private javax.swing.JTextField habitantes5;
    private javax.swing.JTextField habitantes6;
    private javax.swing.JTextField habitantes7;
    private javax.swing.JTextField habitantes8;
    private javax.swing.JTextField habitantes9;
    private javax.swing.JDialog ingresarTanque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lado;
    private javax.swing.JTextField ladoCubico;
    private javax.swing.JLabel largoO;
    private javax.swing.JTextField largoOrt;
    private javax.swing.JTextArea listaTanques;
    private javax.swing.JButton llenarTanque;
    private javax.swing.JButton mostrarAgua;
    private javax.swing.JButton mostrarTanques;
    private javax.swing.JButton mostrarValvulas;
    private javax.swing.JTextField municipio1;
    private javax.swing.JTextField municipio10;
    private javax.swing.JTextField municipio2;
    private javax.swing.JTextField municipio3;
    private javax.swing.JTextField municipio4;
    private javax.swing.JTextField municipio5;
    private javax.swing.JTextField municipio6;
    private javax.swing.JTextField municipio7;
    private javax.swing.JTextField municipio8;
    private javax.swing.JTextField municipio9;
    private javax.swing.JTextField municipioAV;
    private javax.swing.JTextField numeroAV;
    private javax.swing.JTextField numeroLT;
    private javax.swing.JTextField numeroNT;
    private javax.swing.JLabel radio;
    private javax.swing.JTextField radiotxt;
    private javax.swing.JTextField regionCA;
    private javax.swing.JTextField regionNT;
    private javax.swing.JButton seguirNTanque;
    // End of variables declaration//GEN-END:variables
}
